### ISSUE TITLE
Revert ora to support cjs packages

### ISSUE THREAD

**Issue by ItzRabbs** [wan2land/distize#289]
Distize is currently not working with cjs packages because `ora@6` only supports esm packages. Can you revert to `ora@^5.4.1` and add it as a `ignoreDeps` in renovate.json?

I wanted to do this on my own and make a PR, but my attempt completely screws up the package-lock.json file. I think I'm on a different version of node or npm or both.

**Comment by wan2land** [comment]
OMG.. 🥲

**Comment by wan2land** [comment]
Deployed v2.2.2. :-)
I'll be careful when upgrading the package version. Thanks for the issue.
