### ISSUE TITLE
Disable Clean old dist files

### ISSUE THREAD

**Issue by tapz** [wan2land/distize#30]
Just run distize with -o . and the whole project directory vanished into thin air. Please add an option to not destroy anything! Or even better by default not to destroy.

**Comment by wan2land** [comment]
That's a good point.

In `v2` and above, files are not deleted by default. If you want to use it as before, you must use it with the `--clean` option.

```shell
npx distize -o dist # overwrite files
npx distize -o dist --clean # remove dist and copy to dist
```

**Comment by moikarin** [comment]
This is not working with v2.1.1. Or possibly the --no-files interferes.

I ran into this when my Typescript compiler output files got deleted. I would expect that when --no-files is specified, only the node_modules directory gets cleaned up.
```
$ npx distize --no-files --out _build/dist
✔ Clean old dist files, "_build/dist"
✔ Copy node_modules
$ npx distize --version
v2.1.1

```
